name: CI
on:
   push:
    branches: [main]
   pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: run make command
      run: 
      using: 'node16'
      main: 'main.js'
      make hello
 
      
    
    
